// Runtime widget configuration, read from `window.__WIDGET_CONFIG__`.
//
// In production `/config.js` is REGENERATED at container start from the
// WIDGET_CHANNEL_* environment variables (see
// `docker-entrypoint.d/10-widget-config.envsh`), so contact links change with a
// restart — no rebuild, nothing baked into the bundle. In `vite dev` the
// checked-in `public/config.js` supplies empty defaults, so the file never 404s
// and every channel is simply hidden.
//
// The shape is deliberately flat and all-string: the file is generated by a
// shell heredoc, so anything richer would be a quoting hazard.

export interface WidgetRuntimeConfig {
  whatsapp: string;
  telegram: string;
  viber: string;
  facebook: string;
}

declare global {
  interface Window {
    __WIDGET_CONFIG__?: Record<string, unknown>;
  }
}

// `/config.js` is generated outside the type system, so every field is treated
// as untrusted input: anything that is not a non-empty string reads as "unset",
// which hides the channel rather than rendering a broken link.
function readString(source: Record<string, unknown>, key: string): string {
  const value = source[key];
  return typeof value === "string" ? value.trim() : "";
}

export function getRuntimeConfig(): WidgetRuntimeConfig {
  const source = typeof window === "undefined" ? {} : (window.__WIDGET_CONFIG__ ?? {});

  return {
    whatsapp: readString(source, "whatsapp"),
    telegram: readString(source, "telegram"),
    viber: readString(source, "viber"),
    facebook: readString(source, "facebook"),
  };
}
